### ISSUE TITLE
Inferring mutation times

### ISSUE THREAD

**Issue by sylviah23** [popgenmethods/SINGER#17]
After converting to tree sequence format, the tables.mutation.time column is empty currently. Does SINGER infer these mutation times and if so, is it possible to add them in to the tree sequence?

**Comment by YunDeng98** [comment]
Hi @sylviah23 , the mutation time can be calculated using the average of lower and upper node time, does this work for you?

**Comment by sylviah23** [comment]
Hi @YunDeng98, that works, thank you!
