### ISSUE TITLE
multiple trees sequences generated

### ISSUE THREAD

**Issue by mehakmadhura** [popgenmethods/SINGER#18]
Hello!
It would be great if you could explain why the program generates multiple tree sequence files and why the number of trees sequences generated equals the number of samples.
Thanks!

**Comment by YunDeng98** [comment]
Hi @mehakmadhura SINGER is a Bayesian method which draws samples from the posterior distribution, so that is the reason why there are multiple tree sequences returned by the program. The number of samples is default at 100 but you can set it using the `-n` flag.

**Comment by YunDeng98** [comment]
@mehakmadhura the Ne argument only needs to be rough estimate. Also, the most recent version 0.1.8 gets rid of the -Ne argument.

**Comment by mehakmadhura** [comment]
Thank you!
