### ISSUE TITLE
Mapping sample indices in outputs to inputs

### ISSUE THREAD

**Issue by pmckenz1** [popgenmethods/SINGER#19]
Hi, I'm really enjoying working with SINGER so far!

I'm curious about the method by which SINGER maps input samples in the VCF to the integer-named output samples. 

For example, I have an input VCF with names such as: '01_01_06', '01_06_03', '01_08_42', '01_09_05', '01_11_03', etc. There are 109 samples total in the VCF. 

I run singer: 

`../pkgs/SINGER/releases/singer-0.1.7-beta-linux-x86_64/singer_master -Ne 5e4 -m 1.0e-8 -vcf ../june21polarized_singer_data -output singer5e4 -start 22289000 -end 22324000 -n 1000 -thin 10 -polar 0.99`

And then I run the convert_to_tskit code: 

`../pkgs/SINGER/releases/singer-0.1.7-beta-linux-x86_64/convert_to_tskit -input singer5e4 -output singertskit -start 100 -end 1000 -step 10`

The output trees have 218 tips, numbered from 1 to 218, each representing a chromosome from the original VCF. **Is there a simple way to map these tips back to sample names of the 109 input individuals?** 

Thanks so much!
Patrick

**Comment by YunDeng98** [comment]
Hi @pmckenz1 the order of the tree sequence leaf nodes is simply the original same order in the vcf file. For example, the first individual contribute to leaf node 0 and 1, the second to leaf node 2 and 3, and so on.

**Comment by pmckenz1** [comment]
Hi @YunDeng98 makes sense - thanks so much!
