### ISSUE TITLE
Correspondence between the positions in SINGER's output and the positions in the input VCF file

### ISSUE THREAD

**Issue by jitang-github** [popgenmethods/SINGER#23]
Hi @YunDeng98,

Both the principle and the implementation of SINGER look so cool! 

After converting the output to Tree Sequence with tskit, I found that the positions in the `tree.interval` and `trees.sites_position` are different from those in the input VCF. I noticed the number of the positions in the `trees.sites_position` is the same as the number of those in the input VCF, can I assume that the positions in `trees.sites_position` correspond one to one with those in the input VCF in ascending order? 

I also noticed the left position in the `tree.interval` seem to always start from 0, to make the positions in `tree.interval` comparable to those in the input VCF, would it be correct to just add the first position in the VCF to each of the positions in `tree.interval`?

Looking forward to your reply at your convenience. Thanks!

**Comment by YunDeng98** [comment]
Hi @jitang-github thanks for your message. Just to make sure I understand your request clearly, you are asking about the discordance between the polymorphic site information in VCF file versus the the site positions in the inferred tree sequences, right? If I got the idea correctly, would you mind you send me a small example? Just some random screenshots will do it, thanks!

**Comment by jitang-github** [comment]
Hi @YunDeng98, thanks for your reply. Yes, you are right. Please check the screenshot below for an example of the discordance. Seems like we will not observe the discordance when working on the genomic regions with coordinates starting from 0 (like simulation data). 

I have written a function that can modify the positions in `trees.sites_position` to make them correspond one-to-one with those in the input VCF and modify the positions in `tree.interval` to make them comparable to those in the input VCF, but I am not quite sure if there are any problems, please check below for it (Looks github does not support .py file, please delete the .txt before opening it). 

If you find that I am making any mistakes or need more information, please let me know, thanks!

![image](https://github.com/user-attachments/assets/278c07a8-1082-4c85-bf83-cafc3de83879)

[modify_positions_in_singer_trees.py.txt](https://github.com/user-attachments/files/17104788/modify_positions_in_singer_trees.py.txt)

**Comment by YunDeng98** [comment]
@jitang-github thanks for the detailed information you sent. What is the -start and -end flag you used?

**Comment by jitang-github** [comment]
Hi, @YunDeng98, I am working with a data spanning whole-genome and with ~2k individuals (actually if time cost allows it is better to work with the whole data with >5k individuals), so I split the genomes into chunks, each with 500 SNPs. I am running SINGER on each of the chunks parallelly, the -start and -end take in the first and last positions in each chunk respectively

**Comment by jitang-github** [comment]
Hi, @YunDeng98, the reply makes sense a lot, you have solved my questions. Many thanks!
