### ISSUE TITLE
Auto-debug failed for customized VCF input data

### ISSUE THREAD

**Issue by dandanpeng** [popgenmethods/SINGER#5]
Hi, @YunDeng98,

For some reason, I need to use ms to simulate the haplotypes. I wrote a script to transfer the ms output file to VCF format since ms cannot directly output VCF. Here is the command I used to run Singer with the customized VCF:

`~/singer_master -Ne 10000 -m 2e-8 -ratio 1.25 -start 1 -end 100 -vcf ms -output ms -n 2 -thin 20`

The error message says: 

> singer: Scaler.cpp:176: void Scaler::rescale(ARG&, double): Assertion `new_t >= old_t' failed.

Do you have any ideas about the reason for this error message? Thank you!

**Comment by YunDeng98** [comment]
Hi @dandanpeng, I guess your vcf is haplotype-based? If so, for now SINGER only supports diploid vcf files, meaning that the genotypes must appear like `0|0`, `0|1` etc. However, I can write you a new test parser of haploid vcf if I am correct with the vcf file format.

**Comment by dandanpeng** [comment]
I've forced the genotype to be 0|0, 0|1 formatted. So I guess that's not the issue.

**Comment by YunDeng98** [comment]
I think your sequence is only 100bp long? if so may I ask how many variants are there in the region? SINGER will likely not work if the number of variants is fewer than a few hundreds.

**Comment by dandanpeng** [comment]
The simulated sequence is 200kb, and I have 1030 variants for 150 individuals (300 haplotypes).

**Comment by YunDeng98** [comment]
in that case you should use `-start 0` and `-end 2e5` as these parameters stand for the span of the genomic region, the command you used forced SINGER to only read the first 100bp, and then it didn't see enough mutations to estimate ARG.

**Comment by dandanpeng** [comment]
That solves my issue. Thank you!
