### ISSUE TITLE
Scalability of Singer

### ISSUE THREAD

**Issue by dandanpeng** [popgenmethods/SINGER#6]
Hi, @YunDeng98, I learned from the paper that we could run Singer with tens of or hundreds of sequences. Have you tried Singer with thousands of sequences? I wonder if Singer can handle that sample size. Thank you!

**Comment by YunDeng98** [comment]
Hi @dandanpeng The scalability of SINGER is on hundreds of WGS, as mentioned in the first paragraph in the Discussion Section. The mentioning of "tens or hundreds of thousands" is probably in the abstract/introduction when describing other methods like tsinfer/ARG-Needle, not SINGER. I personally tried 500 sequences, but not more than that. I wouldn't recommend running SINGER for thousands of sequences.
